# Generated by Django 4.0.1 on 2022-01-10 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='village_city',
        ),
        migrations.AddField(
            model_name='user',
            name='house_building_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=15),
        ),
    ]
